paths: {
  local: ${DREMIO_HOME}"/data"

  # diretório para spill de operações de sort/hash que excedem memória
  spilling: ["/tmp/dremio/spill"]
}

services: {
  coordinator.enabled: true,
  coordinator.master.enabled: true,
  executor.enabled: true,
  flight.use_session_service: true
}
